
/*============================================================================
Filename : touch_example.c
Project : QTouch Modular Library
Purpose : Provides sample code snippet to demonstrate how to process and get status from
          touch library.

This file is part of QTouch Modular Library example application.

Important Note: Do not edit this file manually.
                Use QTouch Configurator within Atmel Start to apply any
                modifications to this file.

Usage License: Refer license.h file for license information
Support: Visit http://www.microchip.com/support/hottopics.aspx
               to create MySupport case.

------------------------------------------------------------------------------
Copyright (c) 2020 Microchip. All rights reserved.
------------------------------------------------------------------------------
============================================================================*/

/*----------------------------------------------------------------------------
 *     include files
 *----------------------------------------------------------------------------*/
#include <atmel_start.h>
#include <rstctrl.h>
#include "touch_example.h"
/*----------------------------------------------------------------------------
 *   Extern variables
 *----------------------------------------------------------------------------*/
extern volatile uint8_t measurement_done_touch;

/*----------------------------------------------------------------------------
 *   Global variables
 *----------------------------------------------------------------------------*/
uint8_t key_status = 0;
uint8_t sw0_debounce = 0;

/*----------------------------------------------------------------------------
 *   prototypes
 *----------------------------------------------------------------------------*/
void touch_status_display(void);
void sample_reset_switch(void);

/*----------------------------------------------------------------------------
 *   function definitions
 *----------------------------------------------------------------------------*/

/*============================================================================
void touch_example(void)
------------------------------------------------------------------------------
Purpose: This function provides sample code snippet to process and check the
         status of touch library
Input  : none
Output : none
Notes  : The content on this function has to be copied to the main() function
         on main.c file.
============================================================================*/

void touch_example(void)
{

	/*
	 * This touch example project demonstrates the usage of QTouch Library firmware for developing touch applications.
	 * To enable sensor tuning, the associated debug information can further be monitored using Atmel Data Visualizer
	 * GUI.
	 *
	 * The following Atmel Start peripheral drivers have been used in this example project along with QTouch Library
	 * middleware.
	 * 1. System Clock - To set CPU clock.
	 * 2. Timer/RTC - To provide periodic scan interval to initiate touch measurement.
	 * 3. USART - To relay touch debug information via EDBG or mEDBG USB bridge to Atmel Data Visualizer GUI.
	 * 4. Global system interrupt should be enabled.
	 *
	 * Note: This is a sample file to provide reference on using touch status in a user application. This file is not
	 * linked to a project build.
	 */

	cpu_irq_enable(); /* Global Interrupt Enable */

	touch_process();
	if (measurement_done_touch == 1) {
		measurement_done_touch = 0;
		touch_status_display();

		sample_reset_switch();	// Used during development; may not be required in your application
		// Note that the UPDI pin also serves as an external hardware reset input but only if enabled by fuses.
		// If set to external hardware reset with fuses, then the UPDI function is not available.  This is very inconvenient during development.
	}
}

/*============================================================================
void touch_status_display(void)
------------------------------------------------------------------------------
Purpose: Sample code snippet to demonstrate how to check the status of the
         sensors
Input  : none
Output : none
Notes  : none
============================================================================*/
void touch_status_display(void)
{
	uint8_t i = 0;
	
	key_status = 0;
	for (i = 0; i < DEF_NUM_SENSORS; i++) {
		if (0u != (get_sensor_state(i) & KEY_TOUCHED_MASK)) {
			key_status |= 1 << i;
		}
	}

    // Note if any key is pressed
    if (0u != key_status) {
	    LED_set_level(false);	// LED on
	    } else {
	    LED_set_level(true);	// LED off
    }

    // PROXIMITY - UNSHIELDED
	if (0u != (key_status & (1<<0))) {
        LED0_set_level(false);	// LED on
	} else {
        LED0_set_level(true);	// LED off    
    }

    // PROXIMITY - DRIVEN SHIELD    
    if (0u != (key_status & (1<<1))) {
        LED3_set_level(false);	// LED on
     } else {
        LED3_set_level(true);	// LED off
    }

    // BUTTON1
    if (0u != (key_status & (1<<2))) {
	    LED1_set_level(false);	// LED on
	    } else {
	    LED1_set_level(true);	// LED off
    }

    // BUTTON2
    if (0u != (key_status & (1<<3))) {
	    LED2_set_level(false);	// LED on
	    } else {
	    LED2_set_level(true);	// LED off
    }
}

void sample_reset_switch(void)
{
	/* Check the status of SW0 User Button on ATTINY3217-XPRO*/
	/* 0: Pressed */
	/* If pressed, reset the system */
	if (!PB5_get_level()) {
		sw0_debounce++;	// indicate pressed
	}
	else {
		sw0_debounce = 0;	// indicate released
	}
	
	if (sw0_debounce == 0x03 )	// check that SW0 has been held for 3 consecutive samples
	{
		RSTCTRL_reset(); /* Assert Software Reset */
	}
}
